FROM microsoft/mssql-server-linux
MAINTAINER Jared Atkinson <jared@invoke-ir.com>

RUN mkdir -p /usr/src/ace
WORKDIR /usr/src/ace

COPY import-data.sh /usr/src/ace
COPY ace.sql /usr/src/ace

RUN chmod +x /usr/src/ace/import-data.sh

CMD /bin/bash /usr/src/ace/import-data.sh $SA_PASSWORD